### ISSUE TITLE
Cannot get console keys to verify properly

### ISSUE THREAD

**Issue by FlameSlap** [Myster-Tee/NxFileViewer#11]
It always says the following no matter what game I check/dump from my switch. Why is that or what am I doing wrong? What is the purpose of console.keys? Perhaps a template would help and an explanation on what to do or why they are needed. Prod and title keys load and work just fine with no issues. I am only having trouble with the console.keys or perhaps it is something I just dont understand.

Failed to match key device_key_4x
Failed to match key eticket_rsa_kek_personalized
Failed to match key eticket_rsa_kek_source
Failed to match key eticket_rsa_kekek_source
Failed to match key save_mac_key
Failed to match key ssl_rsa_kek_source
Failed to match key ssl_rsa_kekek_source
Failed to match key ssl_rsa_key

**Comment by Lyko01Bytes** [comment]
This may sound really dumb, but I think you answered your own question. Well, sort of. Usually, warnings like this can be ignored and applications such as mine or yours would work when extracting or dumping unless required.

If it fails to match the associated keys, the issue is not the key, but the template as one states to that of the app may work regardless but I could be wrong. If it is not required by the app in the code, then obviously it might not work for that specific key or hash or may already be in part of the machine. Or the code to the app was altered and it would need adjusting. This means that one has used a version not associated to the program which is why the requirement for the keys unless fixed - say for example, I updated my hactool or application file after its release.

Read the note below.

I am shocked that the product keys remain the same, while others do know that the windows hash to more if using emulator or similar. As in this case for example, the console keys are variously or closely generic. One might say the product key works but have you tried substituting the console keys as the product key and include the keys with the console or substitute it with all keys? - for the file name. Meaning, the file console.keys, is just another key-file. (so, kind of pointless). 

Think of Yuzu and Rejujinx as two separate applications or the console combined, while the product keys, are the firmware to use it. As far as title keys are concerned, they work, I guess for the firmware version one is trying to use. Thus, in the firmware associated, you would need a generic install factor on this to get your console though all keys should be included. If it does not match, recommends using the proper hash if able to be found. I think of OLED, or Mariko keys but really this should not matter and is an opinion. It should be generic. One is a switch, and the other the switch lite. This is just a guess.

If each system made had its own digital id, just find old switch code. The keys are already there, but if there were a generic switch, then each console would not be unique.
