### ISSUE TITLE
Title Key auto-extraction from nsp-ncz

### ISSUE THREAD

**Issue by buggii** [Myster-Tee/NxFileViewer#2]
I don't know if this can be done but the encrypted title key is contained inside the ticket file (.tik) at offset 0x180 (16 bytes). With this info is it possible to get rid of the title.keys file making the program to auo-load the key from that file ?

**Comment by Myster-Tee** [comment]
Humm very interesting, I didn't know about that, I'll have a look at this. Thanks

**Comment by Myster-Tee** [comment]
Implemented in v2.4.0

**Comment by Ammako** [comment]
Title keys for legit eshop content with personalized tickets are 100h bytes long and use a different format that NxFileViewer doesn't seem to be able to handle. The NCAs are identical regardless.

https://switchbrew.org/wiki/Ticket

I'm not sure if this is something that could be supported; it would at the very least require dumping your own keys so you have your own console-unique keys.

Otherwise it would be worthwhile to check for personalized tickets (title key type 1) and show a warning instructing the user to dump their title keys, because the current way has misled people already into thinking that their files were corrupt (https://github.com/rashevskyv/dbi/issues/223) when they were actually fine, NxFileViewer is just incorrectly reading the first 16-bytes of the entire title key block and trying to use that as a valid title key, which of course fails.

(For what it's worth, Lockpick RCM seems to know how to convert between title key type 1 and 0, so you might be able to get the logic from its source code and implement support for it natively instead of making users dump their keys.)

One more thing to note: newer versions of Lockpick put console-unique keys inside prod.keys; the separate console.keys file does not exist anymore.

Or... is this supported already, given that there is the option of providing the console-unique keys? In which case, it should differentiate between title key types regardless and show a clearer error when trying to read files with title key type 1 and console-unique keys aren't provided.
